### ISSUE TITLE
How do you open your terminal in atom? That's so cool!

### ISSUE THREAD

**Issue by amilajack** [ericclemmons/npm-install-webpack-plugin#19]

**Comment by LongLiveCHIEF** [comment]
:+1:

**Comment by yusiswtor** [comment]
Search for terminal in the package install window. I prefer https://atom.io/packages/terminal-plus

**Comment by ericclemmons** [comment]
@amilajack Thanks!  I spent a few hours getting it setup just right for the demo!

I'm using [term3][1], as all of the other terminal windows (including `terminal-plus`) had major issues for me.

In fact, if you install it and then go to `Atom > Open Your Config`, you can use my color scheme + settings!

```yaml
  term3:
    colors:
      background:
        red: 37
        green: 50
        blue: 57
        alpha: 1
      brightBlack:
        red: 0
        green: 40
        blue: 52
        alpha: 1
      brightBlue:
        red: 131
        green: 148
        blue: 150
        alpha: 1
      brightCyan:
        red: 147
        green: 161
        blue: 161
        alpha: 1
      brightGreen:
        red: 88
        green: 110
        blue: 117
        alpha: 1
      brightRed:
        red: 203
        green: 76
        blue: 21
        alpha: 1
      brightWhite:
        red: 254
        green: 247
        blue: 227
        alpha: 1
      brightYellow:
        red: 101
        green: 123
        blue: 131
        alpha: 1
      foreground:
        red: 131
        green: 148
        blue: 150
        alpha: 1
      normalBlack:
        red: 0
        green: 53
        blue: 64
        alpha: 1
      normalBlue:
        red: 39
        green: 139
        blue: 210
        alpha: 1
      normalGreen:
        red: 132
        green: 153
        blue: 1
        alpha: 1
      normalPurple:
        red: 211
        green: 54
        blue: 130
        alpha: 1
      normalRed:
        red: 220
        green: 49
        blue: 47
        alpha: 1
      normalWhite:
        red: 238
        green: 232
        blue: 213
        alpha: 1
      normalYellow:
        red: 181
        green: 137
        blue: 0
        alpha: 1
    fontFamily: "Monaco"
    fontSize: "12"
    openPanesInSameSplit: true
```

[1]: https://atom.io/packages/term3
